In [1]:
import numpy as np

In [4]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])
C = np.array([[1,2],[3,4],[5,6]])
E = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
A = np.vstack([v1,v2,v3])
B = np.column_stack([v1,v2,v3])

D = np.column_stack([C,v3])


In [8]:
print(E[0][3], E[1][2])

4 7


In [23]:
print(E[:2,2])

[3 7]


In [24]:
print(E[:2,2:4])

[[3 4]
 [7 8]]


In [20]:
print(E[2,:])

[ 9 10 11 12]


In [21]:
E[0][0]=-1

In [22]:
E

array([[-1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])