In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
path = os.getcwd()

In [4]:
path

'C:\\Users\\user\\Desktop\\usegit (1)\\pytest'

In [5]:
path1 = os.path.join(path,'iris.csv')

In [6]:
path1

'C:\\Users\\user\\Desktop\\usegit (1)\\pytest\\iris.csv'

In [199]:
data = pd.read_csv(path1,sep=',')

In [200]:
data

sepal_length   sepal_width  petal_length  petal_width           class
0              5.1          3.5           1.4          0.2     Iris-setosa
1              4.9          3.0           1.4          0.2     Iris-setosa
2              4.7          3.2           1.3          0.2     Iris-setosa
3              4.6          3.1           1.5          0.2     Iris-setosa
4              5.0          3.6           1.4          0.2     Iris-setosa
..             ...          ...           ...          ...             ...
145            6.7          3.0           5.2          2.3  Iris-virginica
146            6.3          2.5           5.0          1.9  Iris-virginica
147            6.5          3.0           5.2          2.0  Iris-virginica
148            6.2          3.4           5.4          2.3  Iris-virginica
149            5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [248]:
data['petal_length']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [254]:
data.loc[:,['class','petal_length']]

class  petal_length
0       Iris-setosa           1.4
1       Iris-setosa           1.4
2       Iris-setosa           1.3
3       Iris-setosa           1.5
4       Iris-setosa           1.4
..              ...           ...
145  Iris-virginica           5.2
146  Iris-virginica           5.0
147  Iris-virginica           5.2
148  Iris-virginica           5.4
149  Iris-virginica           5.1

[150 rows x 2 columns]

In [10]:
Y = data['class']

In [249]:
X = data.drop(['class'],axis=1)

In [141]:
np.unique(np.array(Y),return_counts=True)

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([50, 50, 50], dtype=int64))

In [25]:
test = np.array(X)

In [238]:
def train_test_split(X,Y,test_size=0.2,validation_size=0.2, random=False, random_seed = None):
    test_size_len = round(test_size *len(X))
    validation_size_len = round(validation_size*len(X))
    indices = np.array(range(len(X)))
    X= np.array(X)
    Y= np.array(Y)
    if random==True:
        
        if random_seed !=None:
            random_generator = np.random.RandomState(random_seed)
            random_generator.shuffle(indices)
            
            test_indices = indices[0:test_size_len]
            validation_indices = indices[test_size_len:test_size_len+validation_size_len]
            train_indices = indices[test_size_len+validation_size_len:]
            
        else :
            np.random.shuffle(indices)
            test_indices = indices[0:test_size_len]
            validation_indices = indices[test_size_len:test_size_len+validation_size_len]
            train_indices = indices[test_size_len+validation_size_len:]
        
        X_train = X[train_indices,:]
        Y_train = Y[train_indices]
        X_test = X[test_indices, :]
        Y_test = Y[test_indices]
        X_validation= X[validation_indices,:]
        Y_validation= Y[validation_indices]
    
    else :
        X_train = X[0:len(X)-test_size_len-validation_size_len,:]
        Y_train = Y[0:len(X)-test_size_len-validation_size_len]
        X_test = X[len(X)-test_size_len-validation_size_len:len(X)-validation_size_len,:]
        Y_test = Y[len(X)-test_size_len-validation_size_len:len(X)-validation_size_len]
        X_validation= X[len(X)-validation_size_len,:]
        Y_validation= Y[len(X)-validation_size_len:]
        
    return X_train, Y_train, X_test, Y_test, X_validation, Y_validation
        

In [240]:
X_train, Y_train, X_test, Y_test, X_validation, Y_validation = train_test_split(X,Y,test_size=0.2, validation_size = 0.2, random=True, random_seed = 30)

In [171]:
def euclidean_dist(obs1,obs2):
    return np.sqrt(np.sum((obs1-obs2)**2))
    

In [172]:
def manhattan_dist(obs1,obs2):
    return np.sum(np.abs(obs1-obs2))

In [241]:
Y_test.shape

(30,)

In [242]:
Y_validation.shape

(30,)

In [243]:
Y_train.shape

(90,)

In [153]:
def search_neighbors(X_train, test_sample,k=5):
    dists_info = list()
    
    for index, train_sample in enumerate(X_train):
        dist = euclidean_dist(test_sample,train_sample)
        dists_info.append((dist,index,train_sample))
        
    dists_info.sort()
    
    return dists_info[:k]

In [154]:
def search_neighbors2(X_train,test_sample,k=5):

    dists_info = list()
    
    for index,train_sample in enumerate(X_train):
        dist = manhattan_dist(train_sample,test_sample)
        dists_info.append((dist,index,train_sample))
        
    dists_info.sort(key=lambda x : x[0])
    
    return dists_info[:k]

In [155]:
ne = search_neighbors2(X_train,obs1,k=3)

In [156]:
ne

[(0.0, 1, array([4.9, 3. , 1.4, 0.2])),
 (0.2000000000000005, 45, array([4.8, 3. , 1.4, 0.3])),
 (0.20000000000000054, 12, array([4.8, 3. , 1.4, 0.1]))]

In [157]:
ne

[(0.0, 1, array([4.9, 3. , 1.4, 0.2])),
 (0.2000000000000005, 45, array([4.8, 3. , 1.4, 0.3])),
 (0.20000000000000054, 12, array([4.8, 3. , 1.4, 0.1]))]

In [180]:
def knn_predict(X_train,Y_train,test_sample,k=5):
    neighbors = search_neighbors2(X_train,test_sample,k)
    
    ne_index = [nei[1] for nei in neighbors]
    
    pred_Y = Y_train[ne_index]
    
    classes, counts = np.unique(pred_Y,return_counts=True)
    pred_sample = classes[np.argmax(counts)]
    return pred_sample

In [177]:
pred_sample, pred = knn_predict(X_train,Y_train,X_train[99,:],k=50)

In [179]:
np.unique(pred,return_counts=True)

(array(['Iris-versicolor', 'Iris-virginica'], dtype=object),
 array([17, 33], dtype=int64))

In [183]:
pred_set = list()

for index, test_sample in enumerate(X_test):
    pred = knn_predict(X_train,Y_train,test_sample,k=5)
    pred_set.append(pred)

In [185]:
sum(pred_set==Y_test)

35

In [186]:
total_accuracy = sum(pred_set==Y_test)/len(Y_test)

In [187]:
total_error_rate = sum(pred_set!=Y_test)/len(Y_test)

In [189]:
print('정확도 : {:.2f} \n오류확률 : {:.2f}'.format(total_accuracy*100, total_error_rate*100))

정확도 : 92.11 
오류확률 : 7.89


In [193]:
class Knn :
    def __init__ (self, k=5):
        self.k = k
        self.neighbors =None
    
    def euclidean_dist (self, obs1, obs2):
        return np.sqrt(np.sum((obs1-obs2)**2))
    
    def search_neighbors (self, X_train, test_sample):
        dists_info = list()
        for index, train_sample in enumerate(X_train):
            dist = self.euclidean_dist(train_sample,test_sample)
            dists_info.append((dist,index,train_sample))
            
        dists_info.sort(key=lambda x:x[0])
        self.neighbors = dists_info[0:self.k]
        return self.neighbors
    
    def predict(self, X_train, test_sample, Y_train):
        pred_set = list()
        self.neighbors =  self.search_neighbors(X_train,test_sample)
        neigh_index = [info[1] for info in self.neighbors]
        
        neigh_Y = Y_train[neigh_index]
        
        classes, counts = np.unique(neigh_Y,return_counts=True)
        pred_Y = classes[np.argmax(counts)]
        return pred_Y

In [194]:
knn = Knn(5)

In [195]:
knn.predict(X_train,X_test[4:,],Y_train)

'Iris-versicolor'

In [196]:
total_pred = list()
for test_sample in X_test:
    total_pred.append(knn.predict(X_train,test_sample,Y_train))


In [198]:
total_accuracy = sum(total_pred==Y_test)/len(Y_test)
total_error_rate = sum(total_pred!=Y_test)/len(Y_test)
print('정확도 : {:.2f}\n오류율 : {:.2f}'.format(total_accuracy*100, total_error_rate*100))

정확도 : 92.11
오류율 : 7.89


In [201]:
from sklearn.neighbors import KNeighborsClassifier as sk_Knn

In [202]:
sk_knn = sk_Knn(n_neighbors=5)
sk_knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [203]:
total_sk_pred = list()
for test_sample in X_test:
    sk_pred = sk_knn.predict(test_sample.reshape(1,-1))
    total_sk_pred.append(sk_pred)
    

In [211]:
sk_pred_array =np.array(total_sk_pred)

In [226]:
reshaped = sk_pred_array.reshape(-1)

In [227]:
Y_test

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [228]:
reshaped == Y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [230]:
accuracy = sum(reshaped == Y_test)/len(Y_test) *100

In [231]:
accuracy

92.10526315789474

In [233]:
knn.neighbors

[(0.1414213562373093, 100, array([6.5, 3. , 5.5, 1.8])),
 (0.3872983346207415, 101, array([6.5, 3. , 5.2, 2. ])),
 (0.4358898943540675, 3, array([6.4, 2.8, 5.6, 2.1])),
 (0.45825756949558394, 6, array([6.4, 2.7, 5.3, 1.9])),
 (0.46904157598234314, 68, array([6.5, 3.2, 5.1, 2. ]))]

In [234]:
        neigh_index = [info[1] for info in knn.neighbors]
        
        neigh_Y = Y_train[neigh_index]
        
        classes, counts = np.unique(neigh_Y,return_counts=True)
        pred_Y = classes[np.argmax(counts)]

In [235]:
np.unique(neigh_Y,return_counts=True)

(array(['Iris-virginica'], dtype=object), array([5], dtype=int64))

In [237]:
neigh_index

[100, 101, 3, 6, 68]